### ISSUE TITLE
Generated config.js file is not stable

### ISSUE THREAD

**Issue by mikeyoon** [buddhike/gulp-jspm-build#16]
I noticed that when the resulting config.js file is created, the order of the keys and arrays are unstable due to the usage of JSON.stringify. This can be a real problem in production usage if assets are hashed. I can make a PR to switch to use https://github.com/substack/json-stable-stringify if you'd like.

**Comment by buddhike** [comment]
Sure PR would be nice ;-) Thanks!

**Comment by grofzero** [comment]
@buddhike Thank you very much:)

**Comment by grofzero** [comment]
@buddhike Could you publish the new version to npm? Thank you

**Comment by buddhike** [comment]
@grofzero Done :-). Sorry about the lag.

**Comment by grofzero** [comment]
@buddhike Not a problem, and thanks again:)
