### ISSUE TITLE
system.import dosent open nothing

### ISSUE THREAD

**Issue by darkfrontcode** [buddhike/gulp-jspm-build#7]
When i make a gulp bundle with gulp-jspm-build, it returns to me a file, something like this -> System.registerDynamic("app.js" .., but when i call in my index.html System.import('app.js'), dosent open nothing, even a error was throw in console, can u help with this? How i can open in system.js this kind of file, Thank you.

**Comment by buddhike** [comment]
I've seen this issue when you have an incorrect value in baseURL setting. Also can you please confirm that you don't see any 404s in network tab?
